version: ‘3’
services:
  my-sql-server:
    container_name: 'my-sql-server'
    image: 'my-sql-image'
    ports:
      - 3306:3306

  java-crud-app:
      container_name: 'java_api'
      image: 'soulmor/java-api:2.0'
      ports:
        - 8080:8080
      environment:
#        - SPRING_DATA_SOURCE_URL=jdbc:mysql://my-sql-server:3306/store_database?autoReconnect=true&useSSL=false
#        - DATASOURCE_HOST=mysqldb:3306
#        - DATASOURCE_USER=allow
#        - DATASOURCE_PASSWORD=allow
#        - DATASOURCE_DB=store_database
        SPRING_APPLICATION_JSON: '{
                "spring.datasource.url": "jdbc:mysql://my-sql-server:3306/store_database?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
                "spring.datasource.username": "allow",
                "spring.datasource.password": "allow",
                "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
                "spring.jpa.hibernate.ddl-auto" : "create"
              }'
      depends_on:
        - my-sql-server